-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A, REST_REVIEW AS B
WHERE A.REST_ID = B.REST_ID and A.ADDRESS LIKE "서울%"
GROUP BY B.REST_ID
ORDER BY AVG(B.REVIEW_SCORE) DESC, A.FAVORITES DESC
